services:  
  presenton:  
    # image: ghcr.io/presenton/presenton:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:  
      # Replace 5000 to with port of your choice
      - "5000:80"
    volumes:  
      - ./user_data:/app/user_data

