services:  
  presenton:  
    # image: ghcr.io/presenton/presenton:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:  
      # You can replace 5000 with any other port number of your choice to run Presenton on a different port number.
      - "5000:80"
    volumes:  
      - ./user_data:/app/user_data

  presenton-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development